// Vocabulary: shot sizes, framing, angles, movements, lenses, cutting rules, exposure, light, sound, coverage recipes.
const SIZES = [
  {id:'EST', abbr:'EST', name:'Establishing shot', crop:{cy:52,h:130},
   def:'A wide view of the place before the scene starts inside it. A purpose more than a size: usually as wide as an EWS.',
   use:'The first shot of a new location or a new time. Often the outside of the building, or the whole room.',
   phone:'0.5× on a tripod. Shoot it by day and by night; the edit will want both.'},
  {id:'EWS', abbr:'EWS', name:'Extreme wide shot', crop:{cy:55,h:220},
   def:'The person is small. The place is the point.',
   use:'Open a scene. Show where we are. Show someone alone in a large space.',
   phone:'Use 0.5× or 1×. Put the phone on a tripod and keep the verticals straight.'},
  {id:'WS', abbr:'WS', name:'Wide shot', crop:{cy:48,h:116},
   def:'The whole body, head to feet, with a little room around it.',
   use:'The master shot of a dialogue scene. It shows blocking and body language.',
   phone:'1× works well. Leave a little space above the head and below the feet.'},
  {id:'MWS', abbr:'MWS', name:'Medium wide (cowboy)', crop:{cy:31,h:72},
   def:'Cut at mid-thigh. Westerns used it to keep the holster in frame.',
   use:'Two people who stand and talk. Hands and posture stay visible.',
   phone:'1×. Step back instead of zooming.'},
  {id:'MS', abbr:'MS', name:'Medium shot', crop:{cy:24,h:54},
   def:'Cut at the waist. The neutral, conversational size.',
   use:'Most dialogue. Gestures stay in frame and the face is still clear.',
   phone:'1× or 2×. You will use this size more than any other.'},
  {id:'MCU', abbr:'MCU', name:'Medium close-up', crop:{cy:17,h:36},
   def:'Cut at the chest. Face and shoulders.',
   use:'Dialogue where the words matter more than the actions. The usual size for an over-the-shoulder.',
   phone:'2× if the phone has it. Keep the eyes on the upper third line.'},
  {id:'CU', abbr:'CU', name:'Close-up', crop:{cy:11,h:24},
   def:'The head, cut just below the chin or at the collar.',
   use:'A reaction. A decision. A moment the audience must not miss.',
   phone:'2×, never 0.5×. A wide lens this close stretches the face.'},
  {id:'ECU', abbr:'ECU', name:'Extreme close-up', crop:{cy:7.2,h:6.5},
   def:'One detail: the eyes, a hand, a clock face.',
   use:'Tension, or an insert of an object. Use it rarely and never for long.',
   phone:'2× on a tripod. Tap and hold to lock focus and exposure.'},
];
const FRAMING = [
  {id:'single', abbr:'1S', name:'Single', def:'One person in the frame.',
   use:'Most of your coverage. A clean single has nobody else in it. A dirty single shows the edge of the other person.',
   phone:'Put the eyes on the upper third. Give look room on the side the person faces.'},
  {id:'two', abbr:'2S', name:'Two-shot', def:'Two people in one frame.',
   use:'The master of a conversation. It sets where each person stands.',
   phone:'Shoot it first and let the whole scene play. Everything else must match it.'},
  {id:'ots', abbr:'OTS', name:'Over the shoulder', def:'The back of one head and shoulder in the foreground; the other person faces us.',
   use:'Dialogue. Cut between the two OTS shots and the audience feels the exchange.',
   phone:'Keep both cameras on the same side of the two people. That is the 180-degree rule.'},
  {id:'pov', abbr:'POV', name:'Point of view', def:'The camera sees what the character sees.',
   use:'Right after a close-up of someone looking. Fear, curiosity, discovery.',
   phone:'Hold the phone at the character’s eye height. A little movement helps.'},
  {id:'insert', abbr:'INS', name:'Insert', def:'A close shot of an object or a hand that the scene needs.',
   use:'A clock, a key, a message on a screen. Inserts also hide cuts in the edit.',
   phone:'Shoot every insert you can think of. They save the edit.'},
  {id:'group', abbr:'GS', name:'Group shot', def:'Three or more people in one frame.',
   use:'Meetings, arrivals, anything where the group is the subject.',
   phone:'Go wide, 0.5× or 1×, and stage people at different depths.'},
];
const RULES = [
  {id:'thirds', name:'Rule of thirds', def:'Divide the frame into thirds. Put the eyes on the upper line and the person near a vertical line.',
   use:'A default that almost always looks right. Break it on purpose, not by accident.'},
  {id:'headroom', name:'Headroom', def:'The space between the top of the head and the top of the frame.',
   use:'Tighter shots need less headroom. A close-up can cut the top of the head.'},
  {id:'lookroom', name:'Look room', def:'Extra space on the side the person faces.',
   use:'A person looking left sits on the right of the frame. Also called lead room when they move.'},
];
const ANGLES = [
  {id:'eye', abbr:'EYE', name:'Eye level', def:'The camera is at the subject’s eye height.',
   use:'Neutral. The audience meets the character as an equal.',
   phone:'Raise the tripod to eye height. Most phone tripods are too short, so put it on a table.'},
  {id:'low', abbr:'LOW', name:'Low angle', def:'The camera is below the eyes and looks up.',
   use:'Power, threat, or importance. Ceilings appear behind the person.',
   phone:'Watch for ceiling lights in frame. A wide lens makes the effect stronger.'},
  {id:'high', abbr:'HIGH', name:'High angle', def:'The camera is above the eyes and looks down.',
   use:'Weakness, isolation, or an overview of a space.',
   phone:'A gimbal held overhead works. Tilt the phone down and check the horizon.'},
  {id:'dutch', abbr:'DUTCH', name:'Dutch angle', def:'The camera rolls so the horizon tilts.',
   use:'Unease or disorientation. One or two per film is plenty.',
   phone:'Tilt the tripod head, or lock the gimbal roll and rotate it.'},
  {id:'birds', abbr:'BIRD', name:'Bird’s eye', def:'Straight down from above.',
   use:'Patterns, tables, maps, bodies on the floor.',
   phone:'Clamp the phone to a shelf edge or a boom. Use a self-timer to avoid shake.'},
  {id:'worms', abbr:'WORM', name:'Worm’s eye', def:'Straight up from the ground.',
   use:'Towering people, staircases, ceilings and fans.',
   phone:'Lay the phone on the floor with a small wedge under one end.'},
];
const MOVES = [
  {id:'static', abbr:'STATIC', name:'Static', def:'The camera does not move.',
   use:'Most dialogue. A still frame makes the audience watch the actors.',
   phone:'Tripod. Turn off stabilisation if the frame breathes at the edges.'},
  {id:'pan', abbr:'PAN', name:'Pan', def:'The camera turns left or right on a fixed point.',
   use:'Follow a person who crosses the room. Reveal what is beside them.',
   phone:'Use a fluid tripod head or a gimbal. Start still, move, end still.'},
  {id:'tilt', abbr:'TILT', name:'Tilt', def:'The camera turns up or down on a fixed point.',
   use:'Reveal height. Travel from a face to the object in the hands.',
   phone:'Same as a pan. Keep the speed constant.'},
  {id:'push', abbr:'PUSH', name:'Push in', def:'The whole camera moves toward the subject.',
   use:'A realisation. The audience leans in with the camera.',
   phone:'Gimbal, and walk slowly with bent knees. Very slow is better than slow.'},
  {id:'pull', abbr:'PULL', name:'Pull out', def:'The whole camera moves away from the subject.',
   use:'Isolation, an ending, or a reveal of the wider room.',
   phone:'Walk backwards with a spotter behind you.'},
  {id:'truck', abbr:'TRUCK', name:'Truck (tracking)', def:'The camera moves sideways, often with a walking subject.',
   use:'Walk-and-talk scenes. Passing a row of objects.',
   phone:'Gimbal. Match the actor’s pace, or put the phone on a rolling chair.'},
  {id:'arc', abbr:'ARC', name:'Arc', def:'The camera circles the subject.',
   use:'A turning point, or two people at the centre of something.',
   phone:'Gimbal, small radius, and keep the subject in the same spot of the frame.'},
  {id:'pedestal', abbr:'PED', name:'Pedestal (boom)', def:'The whole camera rises or lowers.',
   use:'Stand up with a character. Reveal a face from behind an object.',
   phone:'Gimbal. Bend and straighten your legs, not your arms.'},
  {id:'zoom', abbr:'ZOOM', name:'Zoom', def:'The lens changes focal length. The camera stays still.',
   use:'Rare in drama. A slow zoom in a static frame can feel uneasy.',
   phone:'Only the jumps between the phone\u2019s real lenses are optical. Smooth zoom in between is digital and soft.'},
  {id:'handheld', abbr:'HH', name:'Handheld', def:'The operator holds the camera. The frame breathes and shakes.',
   use:'Urgency, documentary feel, chaos.',
   phone:'Hold with both hands, elbows in, and keep stabilisation on.'},
  {id:'whip', abbr:'WHIP', name:'Whip pan', def:'A very fast pan that blurs the frame.',
   use:'A cut disguised as a move. A shock reveal.',
   phone:'Whip from a still frame to a still frame. Shoot at 60 fps if you can.'},
];
const LENSES = ['0.5× (13 mm wide)','1× (26 mm)','2× (52 mm)','5× (120 mm telephoto)'];
const LENS_INFO = [
  {id:0, abbr:'0.5×', name:'Ultra wide, 13 mm', bg:.55, stretch:1.12,
   def:'The room grows. Faces stretch near the edges and up close. Straight lines bend at the corners.',
   use:'Establishing shots, cramped spaces, a POV that should feel exposed. Never for a close-up.',
   phone:'Keep the phone level; a tilt bends every vertical. Stand back from faces.'},
  {id:1, abbr:'1×', name:'Wide normal, 26 mm', bg:1, stretch:1.03,
   def:'What a phone photo looks like. A little wider than the eye. Rooms feel their real size.',
   use:'Masters, two-shots, medium shots. Fine for a medium close-up from about a metre and a half.',
   phone:'The main camera, and the best one in low light. When in doubt, use this.'},
  {id:2, abbr:'2×', name:'Normal, 52 mm', bg:1.7, stretch:.98,
   def:'Close to how the eye sees distance. The background steps closer and blurs a little. Faces keep their shape.',
   use:'Singles, over-the-shoulders, close-ups, inserts. The portrait lens of the phone.',
   phone:'On many phones 2× is a crop of the main sensor, not a real lens, so it gets grainy at night. Light the room.'},
  {id:3, abbr:'5×', name:'Telephoto, 120 mm', bg:2.6, stretch:.94,
   def:'Compression. The background leaps forward and goes soft. Faces flatten and look their best.',
   use:'Isolated close-ups, reactions across a room, a face in a crowd. Needs four to five metres for a medium shot.',
   phone:'Only on phones with a telephoto module. Tripod always; the smallest shake shows.'},
];
const RULES_CUT = [
  {id:'line', name:'The 180-degree line', def:'Draw a line between two people who face each other. Keep every camera on one side of it.',
   use:'If you cross it, the two people swap sides of the screen and seem to look the same way. Cross it only with a move that shows the crossing.'},
  {id:'thirty', name:'The 30-degree rule', def:'Between two shots of the same subject, move the camera at least 30 degrees, or change the size by two steps.',
   use:'A smaller change looks like a mistake: a jump cut. WS to MS, or MCU to CU from a new angle, cuts clean.'},
  {id:'eyeline', name:'Eyeline match', def:'If A looks frame-left in her single, B looks frame-right in his. Their eyes should meet across the cut.',
   use:'Set the eyeline just beside the lens, on the side of the other actor. Note the side on the shot list.'},
  {id:'action', name:'Cut on action', def:'Cut in the middle of a movement: the hand reaching, the head turning, the door opening.',
   use:'The movement hides the cut. So shoot the whole action in both sizes, with an overlap, never half in each.'},
];
const EXPOSURE = [
  {id:'shutter', abbr:'1/50', name:'Frame rate and shutter', def:'Shoot at 24 or 25 fps. Set the shutter to double the frame rate: 1/48 or 1/50. This is the 180-degree shutter rule.',
   use:'Always, unless you want a jittery, crisp look for a fight or a panic. Then go faster, on purpose.',
   phone:'The stock camera app picks its own shutter and changes it as the light changes. Use an app that lets you lock it.'},
  {id:'iso', abbr:'ISO', name:'ISO and noise', def:'ISO is the sensor’s gain. Higher ISO brightens the image and adds grain, especially in shadows.',
   use:'Keep it as low as the light allows. A phone looks clean up to about ISO 400 and rough past 800.',
   phone:'If the shot needs ISO 1600, the answer is a lamp, not the ISO slider.'},
  {id:'nd', abbr:'ND', name:'Neutral density filter', def:'Dark glass on the lens. It cuts the light without changing colour, so the shutter can stay at 1/50 in daylight.',
   use:'Every daylight exterior. Without it the phone forces a fast shutter and the motion looks like a phone video.',
   phone:'A clip-on variable ND is the one outdoor accessory that matters. Indoors you will rarely need it.'},
  {id:'wb', abbr:'WB', name:'White balance', def:'The colour the camera calls white. Daylight is blue, tungsten bulbs are orange, LED panels are set by you.',
   use:'Pick one setting for the scene and lock it. Auto white balance drifts between takes and the cut shows a colour jump.',
   phone:'Match the lamps to the window or cover the window. Mixed light is the hardest thing to fix later.'},
  {id:'lock', abbr:'LOCK', name:'Lock everything', def:'Exposure in video is set once and held. Lock shutter, ISO, white balance and focus before the take.',
   use:'Every take of a scene should match every other take. Locks are what make cuts invisible.',
   phone:'A manual camera app gives you the locks; several are free. In the stock app, press and hold to lock focus and exposure at least.'},
];
const LIGHT = [
  {id:'window', abbr:'KEY', name:'The window is your key light', def:'The key is the main light on the face. A window gives a big, soft key for free.',
   use:'Put the actor beside the window, not facing it and not with their back to it. Light from 45 degrees to one side shapes the face.',
   phone:'Daylight changes by the hour. Shoot the whole scene in one sitting, or block the window and use lamps.'},
  {id:'three', abbr:'3-PT', name:'Key, fill, back', def:'Key lights the face. Fill, opposite and weaker, softens the shadow. Back light, behind, separates the head from the wall.',
   use:'The standard setup for a single. With one LED panel, use it as key and a white wall or a sheet as fill.',
   phone:'A cheap LED panel and a white bedsheet on a chair is a real two-light setup.'},
  {id:'soft', abbr:'SOFT', name:'Hard and soft', def:'A small light makes hard shadows with sharp edges. A big light, or a small one through a sheet, makes soft shadows.',
   use:'Soft for faces and dialogue. Hard for threat, night, interrogation, and shafts of light through a door.',
   phone:'A phone sensor struggles with hard contrast. Soft light hides its limits.'},
  {id:'practical', abbr:'PRAC', name:'Practicals', def:'A lamp that appears in the shot: a desk lamp, a torch, a screen. It explains where the light comes from.',
   use:'Night scenes. Put a practical in the wide, then light the close-ups from the same side so it looks like the lamp did it.',
   phone:'Swap the bulb for a brighter one and dim it with a cloth. The lamp itself is often too dim to light the face.'},
  {id:'ratio', abbr:'RATIO', name:'Contrast ratio', def:'How much brighter the key side of the face is than the fill side. Low ratio is flat and friendly. High ratio is dramatic.',
   use:'Comedy and daytime: low ratio. Suspense and night: high ratio.',
   phone:'Check the shadow side on the phone screen. If it turns to black mush, add fill.'},
  {id:'two', abbr:'2-UP', name:'Lighting two people', def:'One key placed between the two actors, on the far side of the line, lights both faces from the camera’s side.',
   use:'Any two-shot and its over-the-shoulders. Place the key once and it works for every angle on that side of the line.',
   phone:'If the key is on the camera side of the line it goes flat. Keep it across the line, toward the back wall.'},
];
const SOUND = [
  {id:'distance', abbr:'30 CM', name:'Distance beats everything', def:'Sound quality falls fast with distance. A mic 30 cm from the mouth beats an expensive mic at 2 metres.',
   use:'Every line of dialogue. If the mic cannot be close, the shot is a wide and you will loop the line later.',
   phone:'The phone’s own mic is 1.5 metres away on a tripod. Never use it for dialogue.'},
  {id:'lav', abbr:'LAV', name:'The lavalier', def:'A small mic clipped at the chest, about a hand’s width below the chin, pointing up.',
   use:'Most of your dialogue. It follows the actor, so it works for moving shots.',
   phone:'A wireless lav that plugs into the phone is the cheapest big upgrade. Hide it under a collar with a small loop of cable to stop rustle.'},
  {id:'boom', abbr:'BOOM', name:'The boom', def:'A mic on a pole held above the frame line, pointed down at the mouth from in front.',
   use:'Two people close together, or when clothing rustle ruins the lav. Sounds more natural than a lav.',
   phone:'A second phone with the wireless receiver on a broom handle works. Watch the top of the frame in every shot.'},
  {id:'tone', abbr:'TONE', name:'Room tone', def:'Thirty seconds of the room with nobody speaking, recorded with the same mic in the same spot.',
   use:'Every location, every setup. The editor pastes it under cuts so the silence between lines does not jump.',
   phone:'Record it before you strike the set. Say “room tone” out loud at the start so the file is easy to find.'},
  {id:'noise', abbr:'HUM', name:'Kill the hum', def:'Fans, air conditioners, fridges and traffic sit under dialogue and cannot be removed cleanly.',
   use:'Before every take: switch off the fan and the AC, close the window, unplug the fridge. Turn them back on between takes.',
   phone:'A room is quiet at midnight and noisy at 3 pm. Schedule dialogue for the quiet hours.'},
  {id:'sync', abbr:'SYNC', name:'Sync and slate', def:'When sound records on a second device, one sharp clap at the start of each take lines them up in the edit.',
   use:'Every take with a separate recorder. Say the scene and shot number, then clap in frame.',
   phone:'If the mic plugs straight into the phone, you get sync for free. Still slate: it labels the take.'},
];
const RECIPES = [
  {id:'dialogue', name:'Two people talking', when:'Two characters, one place, a conversation that carries the scene.', diagram:'line',
   why:'Shoot the whole scene wide first, then move in. The two over-the-shoulder shots are the heart of it: cut between them and the audience feels the exchange. Stay on one side of the line between the actors so they keep facing each other across the cut.',
   watch:'Keep the eyelines consistent: if A looks frame-left in her single, B looks frame-right in his.',
   shots:[
    {size:'EST',framing:'single',angle:'eye',move:'static',lens:0,description:'Establishing shot of the location.'},
    {size:'MWS',framing:'two',angle:'eye',move:'static',lens:1,description:'Master two-shot. Whole scene.'},
    {size:'MCU',framing:'ots',angle:'eye',move:'static',lens:2,description:'Over A’s shoulder onto B.'},
    {size:'MCU',framing:'ots',angle:'eye',move:'static',lens:2,description:'Over B’s shoulder onto A.'},
    {size:'CU',framing:'single',angle:'eye',move:'static',lens:2,description:'Clean single on A. Reactions.'},
    {size:'CU',framing:'single',angle:'eye',move:'static',lens:2,description:'Clean single on B. Reactions.'},
    {size:'ECU',framing:'insert',angle:'high',move:'static',lens:2,description:'Inserts: hands and objects the dialogue refers to.'}]},
  {id:'three', name:'Three people in a room', when:'A meeting, a family table, a third person who changes the balance between two.', diagram:'line',
   why:'Treat it as a series of two-person exchanges inside one group. The master keeps everyone placed. Then cover each pair that actually talks to each other with two-shots and singles. Do not shoot every possible pair; the script tells you which ones matter.',
   watch:'The line moves with the conversation. Draw it between the two who are talking in that moment, and stay on one side of it.',
   shots:[
    {size:'WS',framing:'group',angle:'eye',move:'static',lens:1,description:'Master. All three placed in the room.'},
    {size:'MS',framing:'two',angle:'eye',move:'static',lens:1,description:'Two-shot of the pair that carries the scene.'},
    {size:'MCU',framing:'ots',angle:'eye',move:'static',lens:2,description:'Over the third person onto the pair.'},
    {size:'MCU',framing:'single',angle:'eye',move:'static',lens:2,description:'Dirty single on A.'},
    {size:'MCU',framing:'single',angle:'eye',move:'static',lens:2,description:'Dirty single on B.'},
    {size:'CU',framing:'single',angle:'eye',move:'static',lens:2,description:'Clean single on the one who listens and says little.'},
    {size:'ECU',framing:'insert',angle:'high',move:'static',lens:2,description:'Inserts: the table, the papers, the cups.'}]},
  {id:'walk', name:'Walk and talk', when:'Two people move through a corridor or a street while they speak.',
   why:'Movement hides the cut. Lead them with the camera moving backwards, follow from behind, and give yourself one static wide they walk through. The static wide is the safety net for the edit.',
   watch:'Match the walking pace between takes, or the cut jumps. Mark the floor where the dialogue lines land.',
   shots:[
    {size:'MS',framing:'two',angle:'eye',move:'truck',lens:1,description:'Lead: camera walks backwards in front of them.'},
    {size:'MWS',framing:'two',angle:'eye',move:'truck',lens:1,description:'Follow: camera walks behind them.'},
    {size:'WS',framing:'two',angle:'eye',move:'static',lens:0,description:'Static wide. They walk through the frame.'},
    {size:'MCU',framing:'single',angle:'eye',move:'truck',lens:2,description:'Side track on A, walking.'},
    {size:'MCU',framing:'single',angle:'eye',move:'truck',lens:2,description:'Side track on B, walking.'},
    {size:'MS',framing:'two',angle:'eye',move:'static',lens:1,description:'Where they stop. Static two-shot for the end of the talk.'}]},
  {id:'alone', name:'Someone alone', when:'A character works, waits, or thinks in a room with nobody else.',
   why:'With no dialogue, the shots must do the talking. Start wide to show the loneliness, then move in as the mood changes. Point-of-view shots and inserts show what the character is thinking about. Give yourself one very long static take; silence needs room.',
   watch:'Resist moving the camera to fill the silence. Let the actor fill it.',
   shots:[
    {size:'WS',framing:'single',angle:'high',move:'static',lens:1,description:'Wide from above. Small figure, big room.'},
    {size:'MS',framing:'single',angle:'eye',move:'static',lens:1,description:'Medium. What the character is doing.'},
    {size:'CU',framing:'single',angle:'eye',move:'push',lens:2,description:'Slow push in as something changes.'},
    {size:'MS',framing:'pov',angle:'eye',move:'static',lens:1,description:'POV: what the character looks at.'},
    {size:'ECU',framing:'insert',angle:'high',move:'static',lens:2,description:'Inserts: hands, the object, the screen.'},
    {size:'ECU',framing:'single',angle:'eye',move:'static',lens:2,description:'The eyes. Hold it.'}]},
  {id:'arrival', name:'Someone enters', when:'A door opens and a new person changes the scene.',
   why:'An entrance has three views: the door, the person already inside, and what the newcomer sees. Shoot all three and the edit can choose whose scene it is. The reaction shot of the person inside is usually the most important one.',
   watch:'Shoot the door opening from both sides. You will want the reverse.',
   shots:[
    {size:'EST',framing:'single',angle:'eye',move:'static',lens:0,description:'Establishing shot: the corridor or the outside.'},
    {size:'WS',framing:'single',angle:'eye',move:'static',lens:1,description:'Wide on the door. It opens, the newcomer enters.'},
    {size:'CU',framing:'single',angle:'eye',move:'static',lens:2,description:'Reaction of the person already inside.'},
    {size:'WS',framing:'pov',angle:'eye',move:'static',lens:1,description:'POV from the doorway: the room as the newcomer sees it.'},
    {size:'MS',framing:'single',angle:'low',move:'static',lens:1,description:'The newcomer steps in. Slight low angle.'},
    {size:'MWS',framing:'two',angle:'eye',move:'static',lens:1,description:'Two-shot as they meet.'}]},
  {id:'phone', name:'A phone call', when:'One character on a call. We may or may not see the other side.',
   why:'A call is a dialogue scene with one actor. Cover it like a single: medium, close, and an insert of the phone. If you shoot the other side later, keep the same size and the opposite eyeline direction, so the two halves cut together like an OTS pair.',
   watch:'Record the other actor’s lines live off camera so the timing of pauses is real.',
   shots:[
    {size:'MS',framing:'single',angle:'eye',move:'static',lens:1,description:'Medium. The call from start to end.'},
    {size:'CU',framing:'single',angle:'eye',move:'static',lens:2,description:'Close. The lines that matter.'},
    {size:'ECU',framing:'insert',angle:'high',move:'static',lens:2,description:'Insert: the phone screen, the name, the timer.'},
    {size:'WS',framing:'single',angle:'eye',move:'pull',lens:1,description:'Pull out at the end. Alone with the news.'},
    {size:'CU',framing:'single',angle:'eye',move:'static',lens:2,description:'Other side, if shot: same size, opposite eyeline.'}]},
  {id:'discovery', name:'Finding something', when:'A character notices or finds an object, a message, a clue.',
   why:'Discovery is a three-shot rhythm: the face, the thing, the face again. The order can flip. A move from the face to the object (a tilt, a pan, or a pull out) can replace the cut and feel more like the character’s own attention.',
   watch:'Shoot the object insert with the same light as the wide, or it looks pasted in.',
   shots:[
    {size:'MS',framing:'single',angle:'eye',move:'static',lens:1,description:'Medium. The moment before they notice.'},
    {size:'CU',framing:'single',angle:'eye',move:'static',lens:2,description:'Close. They notice.'},
    {size:'CU',framing:'pov',angle:'high',move:'static',lens:2,description:'POV: the object where they see it.'},
    {size:'ECU',framing:'insert',angle:'high',move:'static',lens:2,description:'Insert: the detail that matters.'},
    {size:'MCU',framing:'single',angle:'eye',move:'tilt',lens:2,description:'Tilt from the object up to the face.'},
    {size:'WS',framing:'single',angle:'high',move:'static',lens:1,description:'Wide. The character with the thing, small in the room.'}]},
  {id:'argument', name:'An argument', when:'Two people who disagree, and the balance of power shifts.', diagram:'line',
   why:'Cover it like a dialogue, but use angle and size to show who is winning. Low angle and tighter sizes on the one with power; high angle and looser sizes on the one losing it. When the balance flips, flip the angles. Dirty singles keep the other person present as a threat at the edge.',
   watch:'Do the loud take last. Voices do not come back.',
   shots:[
    {size:'WS',framing:'two',angle:'eye',move:'static',lens:1,description:'Master. Distance between them tells the story.'},
    {size:'MCU',framing:'ots',angle:'low',move:'static',lens:2,description:'Over the weaker onto the stronger, low angle.'},
    {size:'MCU',framing:'ots',angle:'high',move:'static',lens:2,description:'Over the stronger onto the weaker, high angle.'},
    {size:'CU',framing:'single',angle:'eye',move:'push',lens:2,description:'Push in on the one who turns the argument.'},
    {size:'CU',framing:'single',angle:'eye',move:'static',lens:2,description:'Dirty single on the other, listening.'},
    {size:'ECU',framing:'insert',angle:'high',move:'static',lens:2,description:'Insert: hands, a fist, a held object.'}]},
  {id:'beat', name:'A silent beat', when:'Someone takes in news, makes a decision, or decides to lie.',
   why:'One long take on the face carries the scene. Everything else is there so the editor can shorten it without a jump: a tighter size, a cutaway to what the character thinks about, and a wide from behind that gives the audience room to guess.',
   watch:'Shoot far longer than you think. Editors cut into a beat, never out of it.',
   shots:[
    {size:'MCU',framing:'single',angle:'eye',move:'static',lens:2,description:'The long take. Hold for a full minute.'},
    {size:'CU',framing:'single',angle:'eye',move:'static',lens:2,description:'Closer. Same performance.'},
    {size:'ECU',framing:'single',angle:'eye',move:'static',lens:2,description:'Eyes only. The decision.'},
    {size:'ECU',framing:'insert',angle:'high',move:'static',lens:2,description:'Cutaway: the object of thought.'},
    {size:'WS',framing:'single',angle:'eye',move:'static',lens:1,description:'Wide from behind. The room, the back of the head.'}]},
  {id:'time', name:'Passage of time', when:'Hours pass. Something is made, waited for, or slowly changes.',
   why:'Lock the tripod and do not touch it. The same frame at different times is the cleanest way to show time passing. Between the repeats, collect inserts of the process: hands, tools, the object at different stages.',
   watch:'Mark the tripod feet with tape. If the phone moves a millimetre between takes, the cut jumps.',
   shots:[
    {size:'WS',framing:'single',angle:'eye',move:'static',lens:1,description:'Locked wide. Repeat at each stage, same frame.'},
    {size:'ECU',framing:'insert',angle:'high',move:'static',lens:2,description:'Insert: hands at work.'},
    {size:'ECU',framing:'insert',angle:'high',move:'static',lens:2,description:'Insert: the object at stage one.'},
    {size:'ECU',framing:'insert',angle:'high',move:'static',lens:2,description:'Insert: the object at stage two.'},
    {size:'ECU',framing:'insert',angle:'high',move:'static',lens:2,description:'Insert: the clock, the light through the window.'},
    {size:'CU',framing:'single',angle:'eye',move:'static',lens:2,description:'Face. Tired, then done.'}]},
];
const byId = (list) => Object.fromEntries(list.map(x => [x.id, x]));
const SIZE = byId(SIZES), FRAME = byId(FRAMING), ANGLE = byId(ANGLES), MOVE = byId(MOVES);
